// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADTaV17qZhyg-2zsZOW67fMkfEhp2whKQ',
    appId: '1:1016381801829:web:3674e32b14169d87034d8c',
    messagingSenderId: '1016381801829',
    projectId: 'sp23-bcs-6b',
    authDomain: 'sp23-bcs-6b.firebaseapp.com',
    storageBucket: 'sp23-bcs-6b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUamDqkeV5Xxpz7GQU_M-umsuG0FhOyNA',
    appId: '1:1016381801829:android:c316fd9eccc5cd15034d8c',
    messagingSenderId: '1016381801829',
    projectId: 'sp23-bcs-6b',
    storageBucket: 'sp23-bcs-6b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNJNBBopvSurUb6-D1ZrKZHtKzOcjTlis',
    appId: '1:1016381801829:ios:611ef2ca681af045034d8c',
    messagingSenderId: '1016381801829',
    projectId: 'sp23-bcs-6b',
    storageBucket: 'sp23-bcs-6b.firebasestorage.app',
    iosBundleId: 'com.jamil.ondemandServicesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNJNBBopvSurUb6-D1ZrKZHtKzOcjTlis',
    appId: '1:1016381801829:ios:611ef2ca681af045034d8c',
    messagingSenderId: '1016381801829',
    projectId: 'sp23-bcs-6b',
    storageBucket: 'sp23-bcs-6b.firebasestorage.app',
    iosBundleId: 'com.jamil.ondemandServicesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADTaV17qZhyg-2zsZOW67fMkfEhp2whKQ',
    appId: '1:1016381801829:web:576992664268361f034d8c',
    messagingSenderId: '1016381801829',
    projectId: 'sp23-bcs-6b',
    authDomain: 'sp23-bcs-6b.firebaseapp.com',
    storageBucket: 'sp23-bcs-6b.firebasestorage.app',
  );
}
