// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIxfThq4wDGVnEBbbViR7R3DsuH7BWGh4',
    appId: '1:765046516521:web:23f7108f138d52e4136538',
    messagingSenderId: '765046516521',
    projectId: 'sp23-bcs-6a',
    authDomain: 'sp23-bcs-6a.firebaseapp.com',
    storageBucket: 'sp23-bcs-6a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgXFkDmAU2lQ032C-7tGqbWbTMpuMrUhM',
    appId: '1:765046516521:android:e8d575933d681f28136538',
    messagingSenderId: '765046516521',
    projectId: 'sp23-bcs-6a',
    storageBucket: 'sp23-bcs-6a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAokYZ91Vz4NqX_pKB8YRDP0CJ6HjpN9xg',
    appId: '1:765046516521:ios:466d2aab94a15418136538',
    messagingSenderId: '765046516521',
    projectId: 'sp23-bcs-6a',
    storageBucket: 'sp23-bcs-6a.firebasestorage.app',
    iosBundleId: 'com.jamil.firebaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAokYZ91Vz4NqX_pKB8YRDP0CJ6HjpN9xg',
    appId: '1:765046516521:ios:466d2aab94a15418136538',
    messagingSenderId: '765046516521',
    projectId: 'sp23-bcs-6a',
    storageBucket: 'sp23-bcs-6a.firebasestorage.app',
    iosBundleId: 'com.jamil.firebaseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIxfThq4wDGVnEBbbViR7R3DsuH7BWGh4',
    appId: '1:765046516521:web:b919cb97b7533fb3136538',
    messagingSenderId: '765046516521',
    projectId: 'sp23-bcs-6a',
    authDomain: 'sp23-bcs-6a.firebaseapp.com',
    storageBucket: 'sp23-bcs-6a.firebasestorage.app',
  );
}
