// GENERATED FILE - DO NOT EDIT MANUALLY.
//
// This file was automatically generated by
// tools/generate_flutter_courses.py
// Generated on: 2026-07-28 09:07:09 UTC
//
// Source: assets/flutter_docs/ (category index)
// To regenerate, run: python3 tools/generate_flutter_courses.py
import '../models/app_course.dart';
export 'flutter_add_to_app_courses.dart';
export 'flutter_ai_courses.dart';
export 'flutter_app_architecture_courses.dart';
export 'flutter_brand_courses.dart';
export 'flutter_community_courses.dart';
export 'flutter_contribute_courses.dart';
export 'flutter_cookbook_courses.dart';
export 'flutter_dash_courses.dart';
export 'flutter_data_backend_courses.dart';
export 'flutter_deployment_courses.dart';
export 'flutter_embedded_courses.dart';
export 'flutter_flutter_for_courses.dart';
export 'flutter_install_courses.dart';
export 'flutter_jobs_courses.dart';
export 'flutter_learn_courses.dart';
export 'flutter_packages_plugins_courses.dart';
export 'flutter_perf_courses.dart';
export 'flutter_platform_integration_courses.dart';
export 'flutter_reference_courses.dart';
export 'flutter_release_courses.dart';
export 'flutter_resources_courses.dart';
export 'flutter_security_courses.dart';
export 'flutter_testing_courses.dart';
export 'flutter_tools_courses.dart';
export 'flutter_tos_courses.dart';
export 'flutter_ui_courses.dart';
