// GENERATED FILE - DO NOT EDIT MANUALLY.
//
// This file was automatically generated by
// tools/generate_flutter_courses.py
// Generated on: 2026-07-28 09:07:08 UTC
//
// Source: assets/flutter_docs/jobs/
// To regenerate, run: python3 tools/generate_flutter_courses.py

import 'package:flutter/material.dart';
import '../models/app_course.dart';

final List<AppCourse> flutterJobsCourses = [
  AppCourse(
    id: "jobs",
    title: "Jobs",
    description: "Official Flutter documentation lessons covering Jobs.",
    instructor: "Flutter Team",
    category: "Mobile Development",
    difficulty: "Beginner to Advanced",
    icon: Icons.flutter_dash,
    color: const Color(0xFFFFA726),
    duration: "30m",
    lessons: [
      AppLesson(
        title: "Template",
        body: "title:\nshowToc: false\n\n{% comment %}\nMake a copy of this document within the src/jobs directory\nName it something representative of the role\nRemove the leading underscore (_) to allow the document to be published\nSpecify the full job title in the front matter\nUpdate the sections with a TODO, removing the TODO when complete\n{% endcomment %}\nAbout the team\n\nAbout the position\n\nOur values\nMentorship\n\nUpon joining Google, you will be paired with a formal mentor,\nwho will help guide you in the process of ramping up, forging relationships,\nand learning the systems you'll need to do your job.\nYour manager can also help you find mentors who can coach you\nas you navigate your career at Google. In addition to formal mentors,\nwe work and train together so that we are always learning from one another,\nand we celebrate and support the career progression of our team members.\nInclusion\n\nHere on the Flutter team and at Google, we embrace our differences\nand are committed to furthering our culture of inclusion.\nWork-life balance\n\nOur team also puts a high value on work-life balance.\nStriking a healthy balance between your personal and professional life\nis crucial to your happiness and success here, which is why we aren't focused\non how many hours you spend at work or online. Instead,\nwe're happy to offer a flexible schedule so you can have a more productive and\nwell-balanced life—both in and outside of work.\nJob location\n\nJob responsibilities\n\nQualifications\nMinimum qualifications\n\nPreferred qualifications\n\nTo apply\n\nPlease apply via this Google Careers page.",
        codeSnippet: "",
        hasImage: false,
      ),
      AppLesson(
        title: "Index",
        body: "title: Flutter and Dart team job openings\nshortTitle: Open jobs\ndescription: Open job listings for the Flutter and Dart teams.\n\nCurrent openings\n\nThe Flutter and Dart teams aren't currently hiring.\nThanks for your interest!",
        codeSnippet: "",
        hasImage: false,
      ),
    ],
  ),
];
