// GENERATED FILE - DO NOT EDIT MANUALLY.
//
// This file was automatically generated by
// tools/generate_flutter_courses.py
// Generated on: 2026-07-28 09:07:09 UTC
//
// Source: assets/flutter_docs/tos/
// To regenerate, run: python3 tools/generate_flutter_courses.py

import 'package:flutter/material.dart';
import '../models/app_course.dart';

final List<AppCourse> flutterTosCourses = [
  AppCourse(
    id: "tos",
    title: "Tos",
    description: "Official Flutter documentation lessons covering Tos.",
    instructor: "Flutter Team",
    category: "Mobile Development",
    difficulty: "Beginner to Advanced",
    icon: Icons.flutter_dash,
    color: const Color(0xFFEF5350),
    duration: "15m",
    lessons: [
      AppLesson(
        title: "Index",
        body: "title: Terms of Service\ndescription: The terms of service for the Flutter website.\nshowBreadcrumbs: false\n\nThe Flutter website (the \"Website\") is hosted by Google. By using and / or\nvisiting the Website, you consent to be bound by Google's general\n[Terms of Service][] and [Privacy Policy][].\n\nThe \"Flutter\" name and the Flutter logo\n\n(the \"Flutter Marks\") are trademarks owned by Google and are not included\nwithin the assets licensed under the Creative Commons Attribution 4.0\nInternational License.  Google grants you a non-transferable,\nnon-exclusive, royalty-free limited license to use the Flutter Marks\nsubject to your compliance with the Flutter Brand Guidelines.\nExcept as set forth above, nothing herein grants or should be deemed\nto grant to you any right, title or interest in or to the Flutter Marks.\n\nAs noted above, Google owns the Flutter trademarks, but we license them\nso they can be used by the developer community to support the Flutter\nSDK, including through training materials and other community content.\n\nAt the same time, it's important to make sure that people don't\nuse the marks in ways that could cause confusion or otherwise misuse\nthe marks, so we have prepared brand guidelines that describe the\nallowed uses of the marks. Our goal in protecting the Flutter trademarks\nis to benefit the entire community by ensuring that the marks are only used\nin ways that are consistent with Google's mission to provide a free and open\nsource SDK.",
        codeSnippet: "",
        hasImage: false,
      ),
    ],
  ),
];
