// GENERATED FILE - DO NOT EDIT MANUALLY.
//
// This file was automatically generated by
// tools/generate_flutter_courses.py
// Generated on: 2026-07-28 09:07:09 UTC
//
// Source: assets/flutter_docs/ (category index)
// To regenerate, run: python3 tools/generate_flutter_courses.py
import 'package:flutter/material.dart';
import '../models/app_course.dart';

import 'flutter_add_to_app_courses.dart';
import 'flutter_ai_courses.dart';
import 'flutter_app_architecture_courses.dart';
import 'flutter_brand_courses.dart';
import 'flutter_community_courses.dart';
import 'flutter_contribute_courses.dart';
import 'flutter_cookbook_courses.dart';
import 'flutter_dash_courses.dart';
import 'flutter_data_backend_courses.dart';
import 'flutter_deployment_courses.dart';
import 'flutter_embedded_courses.dart';
import 'flutter_flutter_for_courses.dart';
import 'flutter_install_courses.dart';
import 'flutter_jobs_courses.dart';
import 'flutter_learn_courses.dart';
import 'flutter_packages_plugins_courses.dart';
import 'flutter_perf_courses.dart';
import 'flutter_platform_integration_courses.dart';
import 'flutter_reference_courses.dart';
import 'flutter_release_courses.dart';
import 'flutter_resources_courses.dart';
import 'flutter_security_courses.dart';
import 'flutter_testing_courses.dart';
import 'flutter_tools_courses.dart';
import 'flutter_tos_courses.dart';
import 'flutter_ui_courses.dart';

export 'flutter_add_to_app_courses.dart';
export 'flutter_ai_courses.dart';
export 'flutter_app_architecture_courses.dart';
export 'flutter_brand_courses.dart';
export 'flutter_community_courses.dart';
export 'flutter_contribute_courses.dart';
export 'flutter_cookbook_courses.dart';
export 'flutter_dash_courses.dart';
export 'flutter_data_backend_courses.dart';
export 'flutter_deployment_courses.dart';
export 'flutter_embedded_courses.dart';
export 'flutter_flutter_for_courses.dart';
export 'flutter_install_courses.dart';
export 'flutter_jobs_courses.dart';
export 'flutter_learn_courses.dart';
export 'flutter_packages_plugins_courses.dart';
export 'flutter_perf_courses.dart';
export 'flutter_platform_integration_courses.dart';
export 'flutter_reference_courses.dart';
export 'flutter_release_courses.dart';
export 'flutter_resources_courses.dart';
export 'flutter_security_courses.dart';
export 'flutter_testing_courses.dart';
export 'flutter_tools_courses.dart';
export 'flutter_tos_courses.dart';
export 'flutter_ui_courses.dart';

final List<AppCourse> flutterCourses = [
  ...flutterAddToAppCourses,
  ...flutterAiCourses,
  ...flutterAppArchitectureCourses,
  ...flutterBrandCourses,
  ...flutterCommunityCourses,
  ...flutterContributeCourses,
  ...flutterCookbookCourses,
  ...flutterDashCourses,
  ...flutterDataBackendCourses,
  ...flutterDeploymentCourses,
  ...flutterEmbeddedCourses,
  ...flutterFlutterForCourses,
  ...flutterInstallCourses,
  ...flutterJobsCourses,
  ...flutterLearnCourses,
  ...flutterPackagesPluginsCourses,
  ...flutterPerfCourses,
  ...flutterPlatformIntegrationCourses,
  ...flutterReferenceCourses,
  ...flutterReleaseCourses,
  ...flutterResourcesCourses,
  ...flutterSecurityCourses,
  ...flutterTestingCourses,
  ...flutterToolsCourses,
  ...flutterTosCourses,
  ...flutterUiCourses,
];
