// GENERATED FILE - DO NOT EDIT MANUALLY.
//
// This file was automatically generated by
// tools/generate_flutter_courses.py
// Generated on: 2026-07-28 09:07:08 UTC
//
// Source: assets/flutter_docs/embedded/
// To regenerate, run: python3 tools/generate_flutter_courses.py

import 'package:flutter/material.dart';
import '../models/app_course.dart';

final List<AppCourse> flutterEmbeddedCourses = [
  AppCourse(
    id: "embedded",
    title: "Embedded",
    description: "Official Flutter documentation lessons covering Embedded.",
    instructor: "Flutter Team",
    category: "Mobile Development",
    difficulty: "Beginner to Advanced",
    icon: Icons.flutter_dash,
    color: const Color(0xFF42A5F5),
    duration: "15m",
    lessons: [
      AppLesson(
        title: "Index",
        body: "title: Embedded support for Flutter\ndescription: >\n  Details of how Flutter supports the creation of embedded experiences.\n\nIf you would like to embed Flutter engine into a car,\na refrigerator, a thermostat... you CAN! For example,\nyou might embed Flutter in the following situations:\n\n Using Flutter on an \"embedded device\",\n  typically a low-powered hardware device\n  such as a smart-display, a thermostat, or similar.\n Embedding Flutter into a new operating system or\n  environment, for example a new mobile platform\n  or a new operating system.\n\nThe ability to embed Flutter, while stable,\nuses low-level API and is not for beginners.\nIn addition to the resources listed below, you\nmight consider joining [Discord][], where Flutter\ndevelopers (including Google engineers) discuss\nvarious aspects of Flutter. The Flutter\n[community][] page has info on more community\nresources.\n\n [Custom Flutter Engine Embedders][], on the Flutter wiki.\n The doc comments in the\n  [Flutter engine embedder.h file][] on GitHub.\n The [Flutter architectural overview][] on docs.flutter.dev.\n A small, self-contained [Flutter Embedder Engine GLFW example][]\n  in the Flutter engine GitHub repo.\n An exploration into [embedding Flutter in a terminal][] by\n  implementing Flutter's custom embedder API.\n [Issue 31043][]: Questions for porting flutter engine to\n  a new os might also be helpful.",
        codeSnippet: "",
        hasImage: false,
      ),
    ],
  ),
];
